### ISSUE TITLE
 the licence agreement

### ISSUE THREAD

**Issue by suzune9999** [iyobo/react-spoon#1]
I'd like to know what is the licence agreement for "react-spoon".
The MIT License ?

Thank you.

**Comment by iyobo** [comment]
Absolutely.



Regards,

Iyobo Eki
( <%28647%29%20767-5296>408) 747-9489
iyobose@gmail.com
*LinkedIn <http://ca.linkedin.com/pub/iyobo-eki/5/289/681/>:
**https://www.linkedin.com/pub/iyobo-eki/5/289/681
<https://www.linkedin.com/pub/iyobo-eki/5/289/681>*
Github <https://github.com/buffonomics>: https://github.com/iyobo

**Comment by iyobo** [comment]
License agreement added.
